import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from 'next-themes'
import "./globals.css";
import ThemeToggle from "@/components/ThemeToggle";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ThemeProvider attribute="class">
         <header className="p-4 flex justify-end border-b border-border">
          <ThemeToggle />
        </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
